version: '3.4'

services:

 elasticsearch: 
   image: nshou/elasticsearch-kibana
   container_name: elasticsearch
   ports:
    - "9200:9200"
    - "5601:5601"
   volumes:
    - ./elasticsearch-data:/usr/share/elasticsearch/data
 

 catelogservice.api:
    image: ${DOCKER_REGISTRY}catelogserviceapi
    build:
      context: DotNet
      dockerfile: CatelogService.API/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
 
 app:
    container_name: notification_service
    restart: always
    build: 
      context: Node/NotificationService
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    links:
      - mongo
 
 mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./Node/NotificationService/data:/data/db
    ports:
      - "27017:27017"