apiVersion: v1
kind: Service
metadata:
  name: catalogservice-sqlserver
  labels:
    app: catalogservice
spec:
  ports:
  - port: 1433
    protocol: TCP
    targetPort: 1433
  selector:
    app: sqlserver
  type: LoadBalancer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-pv-claim
  labels:
    app: catalogservice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogservice-sqlserver
  labels: 
    app: catalogservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogservice
  template:
    metadata:
      labels:
        app: catalogservice
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2017-latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            value: "Passw0rd1"
        ports:
        - containerPort: 1433
        volumeMounts:
        - name: sql-persistent-storage
          mountPath: /var/opt/mssql
      volumes:
        - name: sql-persistent-storage
          persistentVolumeClaim:
            claimName: sqlserver-pv-claim