version: '3.4'

services:

 elasticsearch: 
   image: nshou/elasticsearch-kibana
   container_name: elasticsearch
   ports:
    - "9200:9200"
    - "5601:5601"
   volumes:
    - ./elasticsearch-data:/usr/share/elasticsearch/data
 

 catelogservice.api:
    image: ${DOCKER_REGISTRY}catelogserviceapi
    build:
      context: .
      dockerfile: CatelogService.API/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
