// <auto-generated />
using System;
using CatalogService.DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CatalogService.DAL.EF.Migrations
{
    [DbContext(typeof(CatalogServiceDbContext))]
    [Migration("20220303050814_AddProductTypeModel")]
    partial class AddProductTypeModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CatelogService.Model.CatalogBrandModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrandDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MarkDeleted")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("CatalogBrand");
                });

            modelBuilder.Entity("CatelogService.Model.ProductModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailableStocks")
                        .HasColumnType("int");

                    b.Property<Guid?>("CatalogID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MarkDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaxStockThreshold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid?>("PTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RestockThreshold")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CatalogID");

                    b.HasIndex("PTypeID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CatelogService.Model.ProductTypeModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MarkDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("ID");

                    b.ToTable("ProductType");
                });

            modelBuilder.Entity("CatelogService.Model.ProductModel", b =>
                {
                    b.HasOne("CatelogService.Model.CatalogBrandModel", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogID");

                    b.HasOne("CatelogService.Model.ProductTypeModel", "PType")
                        .WithMany()
                        .HasForeignKey("PTypeID");

                    b.Navigation("Catalog");

                    b.Navigation("PType");
                });
#pragma warning restore 612, 618
        }
    }
}
